import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer';
import Provider from '@/components/Provider';
import { Toaster } from "react-hot-toast";
import { ContextProvider } from '@/components/ContextProvider';
import "@uploadthing/react/styles.css";

const inter = Ubuntu({ subsets: ['latin'], weight: ["300", "400", "500", "700"] });

export const metadata: Metadata = {
  title: 'Welcome to Kurigram District',
  description: 'Generated by rakibul hasan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ContextProvider>
      <Provider>
        <html lang="en">
          <body className={inter.className}>
            <Navbar />
            {children}
            <Toaster />
            <Footer />
          </body>
        </html>
      </Provider>
    </ContextProvider>
  )
}
